// Sample Indian doctor data
export const doctors = [
  {
    id: 1,
    name: "Dr. Aditya Sharma",
    specialty: "Cardiology",
    hospital: "Apollo Heart Institute",
    location: "Mumbai, Maharashtra",
    rating: 4.9,
    experience: "15 years",
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    education: "MD - Cardiology, AIIMS Delhi",
    bio: "Dr. Aditya Sharma is a renowned cardiologist with over 15 years of experience in treating heart diseases. He specializes in interventional cardiology and heart failure management.",
    languages: ["English", "Hindi", "Marathi"],
  },
  {
    id: 2,
    name: "Dr. Priya Patel",
    specialty: "Neurology",
    hospital: "Fortis Medical Center",
    location: "Bangalore, Karnataka",
    rating: 4.8,
    experience: "12 years",
    avatar: "https://randomuser.me/api/portraits/women/46.jpg",
    education: "MD - Neurology, Christian Medical College",
    bio: "Dr. Priya Patel is a specialist in neurological disorders with expertise in stroke treatment and neurodegenerative diseases. She is dedicated to providing comprehensive care using the latest advancements in neurological treatments.",
    languages: ["English", "Hindi", "Gujarati", "Kannada"],
  },
  {
    id: 3,
    name: "Dr. Rajesh Gupta",
    specialty: "Pediatrics",
    hospital: "Rainbow Children's Hospital",
    location: "New Delhi, Delhi",
    rating: 4.9,
    experience: "10 years",
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    education: "MD - Pediatrics, Maulana Azad Medical College",
    bio: "Dr. Rajesh Gupta is a compassionate pediatrician who is devoted to the health and wellbeing of children from infancy through adolescence. He focuses on developmental pediatrics and preventive care.",
    languages: ["English", "Hindi"],
  },
  {
    id: 4,
    name: "Dr. Ananya Chatterjee",
    specialty: "Orthopedics",
    hospital: "AMRI Hospitals",
    location: "Kolkata, West Bengal",
    rating: 4.7,
    experience: "18 years",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    education: "MS - Orthopedic Surgery, Medical College Kolkata",
    bio: "Dr. Ananya Chatterjee specializes in sports-related injuries and joint replacements. With extensive experience, she brings specialized knowledge in recovery and rehabilitation protocols.",
    languages: ["English", "Bengali", "Hindi"],
  },
  {
    id: 5,
    name: "Dr. Vikram Singh",
    specialty: "Dermatology",
    hospital: "Manipal Hospital",
    location: "Jaipur, Rajasthan",
    rating: 4.8,
    experience: "9 years",
    avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    education: "MD - Dermatology, SMS Medical College",
    bio: "Dr. Vikram Singh is a board-certified dermatologist specializing in medical and cosmetic dermatology. He has expertise in treating various skin conditions and performing minimally invasive cosmetic procedures.",
    languages: ["English", "Hindi", "Rajasthani"],
  },
  {
    id: 6,
    name: "Dr. Sneha Reddy",
    specialty: "Psychiatry",
    hospital: "KIMS Hospital",
    location: "Hyderabad, Telangana",
    rating: 4.6,
    experience: "14 years",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    education: "MD - Psychiatry, Osmania Medical College",
    bio: "Dr. Sneha Reddy is a psychiatrist who specializes in mood disorders, anxiety, and PTSD. She takes a holistic approach to mental health, combining medication management with therapy techniques.",
    languages: ["English", "Hindi", "Telugu"],
  },
  {
    id: 7,
    name: "Dr. Manish Joshi",
    specialty: "Oncology",
    hospital: "Tata Memorial Hospital",
    location: "Mumbai, Maharashtra",
    rating: 4.9,
    experience: "20 years",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    education: "DM - Oncology, Tata Memorial Hospital",
    bio: "Dr. Manish Joshi is a highly experienced oncologist specializing in medical oncology and targeted therapy for various cancers. He has contributed to several research papers and clinical trials.",
    languages: ["English", "Hindi", "Marathi"],
  },
  {
    id: 8,
    name: "Dr. Kavita Nair",
    specialty: "Gynecology",
    hospital: "Lakeshore Hospital",
    location: "Kochi, Kerala",
    rating: 4.8,
    experience: "16 years",
    avatar: "https://randomuser.me/api/portraits/women/67.jpg",
    education: "MD - Obstetrics & Gynecology, Govt Medical College Trivandrum",
    bio: "Dr. Kavita Nair is a gynecologist with special interest in high-risk pregnancies and minimally invasive surgeries. She is known for her patient-centered approach and expertise in women's health.",
    languages: ["English", "Malayalam", "Tamil", "Hindi"],
  },
  {
    id: 9,
    name: "Dr. Sandeep Mehta",
    specialty: "Ophthalmology",
    hospital: "Sankara Nethralaya",
    location: "Chennai, Tamil Nadu",
    rating: 4.7,
    experience: "12 years",
    avatar: "https://randomuser.me/api/portraits/men/79.jpg",
    education: "MS - Ophthalmology, Madras Medical College",
    bio: "Dr. Sandeep Mehta specializes in cataract surgery, glaucoma management, and corneal disorders. He has performed over 5000 successful eye surgeries with excellent outcomes.",
    languages: ["English", "Hindi", "Tamil"],
  },
  {
    id: 10,
    name: "Dr. Farhan Ahmed",
    specialty: "Cardiology",
    hospital: "Medanta Hospital",
    location: "Gurgaon, Haryana",
    rating: 4.8,
    experience: "19 years",
    avatar: "https://randomuser.me/api/portraits/men/83.jpg",
    education: "DM - Cardiology, GB Pant Hospital",
    bio: "Dr. Farhan Ahmed is an interventional cardiologist with expertise in complex angioplasties and structural heart disease management. He is known for his dedication to cardiac care.",
    languages: ["English", "Hindi", "Urdu"],
  },
  {
    id: 11,
    name: "Dr. Meenakshi Iyer",
    specialty: "Endocrinology",
    hospital: "Aster Medcity",
    location: "Thiruvananthapuram, Kerala",
    rating: 4.6,
    experience: "11 years",
    avatar: "https://randomuser.me/api/portraits/women/89.jpg",
    education: "DM - Endocrinology, PGIMER Chandigarh",
    bio: "Dr. Meenakshi Iyer specializes in diabetes management, thyroid disorders, and hormonal imbalances. She is committed to providing comprehensive care for all endocrine-related conditions.",
    languages: ["English", "Malayalam", "Tamil", "Hindi"],
  },
  {
    id: 12,
    name: "Dr. Arvind Kejriwal",
    specialty: "Pulmonology",
    hospital: "Max Healthcare",
    location: "New Delhi, Delhi",
    rating: 4.7,
    experience: "14 years",
    avatar: "https://randomuser.me/api/portraits/men/92.jpg",
    education: "DM - Pulmonary Medicine, VPCI Delhi",
    bio: "Dr. Arvind Kejriwal is a pulmonologist specializing in respiratory disorders, sleep apnea, and critical care medicine. He has extensive experience in treating various lung conditions.",
    languages: ["English", "Hindi"],
  },
];

export const specialties = [
  "All Specialties",
  "Cardiology",
  "Dermatology", 
  "Neurology",
  "Orthopedics",
  "Pediatrics",
  "Psychiatry",
  "Oncology",
  "Ophthalmology",
  "Gynecology",
  "Endocrinology",
  "Pulmonology",
  "Gastroenterology",
  "Nephrology",
  "Urology"
];

// Only keep the "All Locations" value as we'll now use the Indian states and cities
export const locations = [
  "All Locations",
];
