
// Sample doctor data
export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    hospital: "City Heart Institute",
    location: "New York, NY",
    rating: 4.9,
    experience: "15 years",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    education: "MD - Cardiology, Harvard Medical School",
    bio: "Dr. Sarah Johnson is a board-certified cardiologist with over 15 years of experience in treating heart diseases and conditions. She specializes in preventive cardiology and heart failure management.",
    languages: ["English", "Spanish"],
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Neurology",
    hospital: "Central Medical Center",
    location: "Boston, MA",
    rating: 4.8,
    experience: "12 years",
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    education: "MD - Neurology, Johns Hopkins University",
    bio: "Dr. Chen is a specialist in neurological disorders with particular expertise in stroke treatment and neurodegenerative diseases. He is dedicated to providing comprehensive care using the latest advancements in neurological treatments.",
    languages: ["English", "Mandarin"],
  },
  {
    id: 3,
    name: "Dr. Emma Williams",
    specialty: "Pediatrics",
    hospital: "Children's Wellness Hospital",
    location: "Chicago, IL",
    rating: 4.9,
    experience: "10 years",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    education: "MD - Pediatrics, University of Chicago",
    bio: "Dr. Williams is a compassionate pediatrician who is devoted to the health and wellbeing of children from infancy through adolescence. She focuses on developmental pediatrics and preventive care.",
    languages: ["English", "French"],
  },
  {
    id: 4,
    name: "Dr. Robert Miller",
    specialty: "Orthopedics",
    hospital: "Sports Medicine Clinic",
    location: "Los Angeles, CA",
    rating: 4.7,
    experience: "18 years",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    education: "MD - Orthopedic Surgery, UCLA",
    bio: "Dr. Miller specializes in sports-related injuries and joint replacements. With extensive experience working with professional athletes, he brings specialized knowledge in recovery and rehabilitation protocols.",
    languages: ["English"],
  },
  {
    id: 5,
    name: "Dr. Lisa Patel",
    specialty: "Dermatology",
    hospital: "Skin & Aesthetic Center",
    location: "Miami, FL",
    rating: 4.8,
    experience: "9 years",
    avatar: "https://randomuser.me/api/portraits/women/37.jpg",
    education: "MD - Dermatology, University of Miami",
    bio: "Dr. Patel is a board-certified dermatologist specializing in medical and cosmetic dermatology. She has expertise in treating various skin conditions and performing minimally invasive cosmetic procedures.",
    languages: ["English", "Hindi", "Gujarati"],
  },
  {
    id: 6,
    name: "Dr. James Wilson",
    specialty: "Psychiatry",
    hospital: "Mind Wellness Clinic",
    location: "Seattle, WA",
    rating: 4.6,
    experience: "14 years",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    education: "MD - Psychiatry, University of Washington",
    bio: "Dr. Wilson is a psychiatrist who specializes in mood disorders, anxiety, and PTSD. He takes a holistic approach to mental health, combining medication management with therapy techniques for comprehensive care.",
    languages: ["English"],
  },
];

export const specialties = [
  "All Specialties",
  "Cardiology",
  "Dermatology", 
  "Neurology",
  "Orthopedics",
  "Pediatrics",
  "Psychiatry",
  "Oncology",
  "Ophthalmology",
  "Gynecology",
];

export const locations = [
  "All Locations",
  "New York, NY",
  "Boston, MA",
  "Chicago, IL",
  "Los Angeles, CA",
  "Miami, FL",
  "Seattle, WA",
];
